# BACKUP IF SOMETHING FAILS THIS WILL RUN NORMALLY


import os
import time
import tempfile
import io
import re
from pathlib import Path
from typing import Optional
from dotenv import load_dotenv
import streamlit as st
# google-genai official client
from google import genai
from google.genai import types
import pandas as pd
from datetime import datetime
import requests

dotenv_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=dotenv_path, override=False)  # set override=True if you want .env to overwrite existing env vars

# Optional: nicer mime detection if you want to show file type
try:
    import magic
except Exception:
    magic = None


sel=""

st.markdown("""
    <style>
        /* Center all titles generated by st.title */
        
        body{
            font-family: "Helvetica Neue", Arial, sans-serif;
            }
        h1 {
            text-align: center;
        }

        /* Customize title color */
        h1, h2, h3 {
            color: #4CAF50;
        }

        /* Body text */
        p, .stText {
            font-size: 16px;
            line-height: 1.5;
        }

        /* Buttons */
        div.stButton > button {
            background-color: #4CAF50;
            color: white;
            border-radius: 8px;
            padding: 0.5rem 1rem;
            border: none;
        }

        div.stButton > button:hover {
            background-color: #45A049;
            color: white;
        }

        /* Sidebar header style */
        section[data-testid="stSidebar"] .css-1d391kg {
            font-size: 20px !important;
            color: #4CAF50 !important;
        }
    </style>
""", unsafe_allow_html=True)

# ---- Helpers ----
def sanitize_filename(filename: str) -> str:
    base = Path(filename).name
    safe = re.sub(r"[^A-Za-z0-9._-]", "_", base)
    return safe or f"upload_{int(time.time())}"

def safe_write_tmp(data: bytes, original_name: str) -> str:
    safe_name = sanitize_filename(original_name)
    tmp_dir = tempfile.gettempdir()
    tmp_path = os.path.abspath(os.path.join(tmp_dir, f"{int(time.time())}_{safe_name}"))
    with open(tmp_path, "wb") as out:
        out.write(data)
    return tmp_path

def robust_upload_to_store(client, tmp_path, store_name, config, sidebar_status):
    """
    Try several upload modes (path string, file handle, bytes-io).
    Returns operation object (or raises).
    sidebar_status: dict-like with 'text' and 'progress' callables to update UI in sidebar
    """
    upload_exceptions = []
    op = None

    # Mode 1: path string
    try:
        sidebar_status["text"]("Starting upload (path mode)...")
        op = client.file_search_stores.upload_to_file_search_store(
            file=tmp_path,
            file_search_store_name=store_name,
            config=config
        )
        sidebar_status["text"]("Upload started (path mode).")
    except Exception as e_path:
        upload_exceptions.append(("path", e_path))
        sidebar_status["text"](f"Path upload failed: {e_path}")

    # Mode 2: file handle
    if op is None:
        try:
            sidebar_status["text"]("Trying upload (file-handle mode)...")
            with open(tmp_path, "rb") as fh:
                op = client.file_search_stores.upload_to_file_search_store(
                    file=fh,
                    file_search_store_name=store_name,
                    config=config
                )
            sidebar_status["text"]("Upload started (file-handle mode).")
        except Exception as e_fh:
            upload_exceptions.append(("file_handle", e_fh))
            sidebar_status["text"](f"File-handle upload failed: {e_fh}")

    # Mode 3: BytesIO
    if op is None:
        try:
            sidebar_status["text"]("Trying upload (bytes-io mode)...")
            with open(tmp_path, "rb") as f:
                data = f.read()
            bio = io.BytesIO(data)
            bio.name = Path(tmp_path).name
            op = client.file_search_stores.upload_to_file_search_store(
                file=bio,
                file_search_store_name=store_name,
                config=config
            )
            sidebar_status["text"]("Upload started (bytes-io mode).")
        except Exception as e_bio:
            upload_exceptions.append(("bytes_io", e_bio))
            # All modes failed -> raise with diagnostics
            msg_lines = ["All upload modes failed. Exceptions:"]
            for mode, ex in upload_exceptions:
                msg_lines.append(f"- {mode}: {ex}")
            msg = "\n".join(msg_lines)
            raise RuntimeError(msg)

    return op

def poll_operation(client, op, sidebar_status, timeout=300, interval=2):
    """
    Poll an operation until done or timeout. Updates sidebar_status progress.
    Returns the final op object or last-known op info when timeout reached.
    """
    waited = 0
    sidebar_status["text"]("Polling import status...")
    max_steps = max(1, timeout // max(1, interval))
    step = 0

    # attempt to get a stable operation name/identifier if present
    op_name = None
    try:
        # Many SDK operation objects have .name or .operation_name
        op_name = getattr(op, "name", None) or getattr(op, "operation_name", None)
        # if op is a dict or has .to_dict() with 'name':
        if op_name is None:
            if isinstance(op, dict):
                op_name = op.get("name")
            else:
                try:
                    od = getattr(op, "to_dict", lambda: None)()
                    if isinstance(od, dict):
                        op_name = od.get("name")
                except Exception:
                    pass
    except Exception:
        op_name = None

    while waited < timeout:
        # update progress heuristic
        pct = min(100, int((step / max_steps) * 100))
        try:
            sidebar_status["progress"](pct)
        except Exception:
            pass

        # check a simple 'done' attribute first
        done = getattr(op, "done", None)
        if done is True:
            sidebar_status["text"]("Import operation completed.")
            break

        # attempt a refresh if we have a client.operations.get and an op_name
        try:
            if op_name:
                refreshed = client.operations.get(op_name)
                if refreshed is not None:
                    op = refreshed
            else:
                # if operations.get accepts operation object or name, try both safely
                try:
                    refreshed = client.operations.get(op)
                    if refreshed is not None:
                        op = refreshed
                except Exception:
                    pass
        except Exception:
            # ignore refresh errors; continue polling
            pass

        if getattr(op, "done", False) is True:
            sidebar_status["text"]("Import operation completed (after refresh).")
            break

        time.sleep(interval)
        waited += interval
        step += 1

    if getattr(op, "done", False) is not True:
        sidebar_status["text"]("Import timed out or still running.")
    # final progress set to 100 if done else leave as-is
    try:
        if getattr(op, "done", False):
            sidebar_status
    except Exception:
        pass

    return op


def _find_in_obj(obj, keys):
    """Recursively search obj (dict/list) for the first value matching any key in `keys` (case-insensitive)."""
    if obj is None:
        return None
    if isinstance(obj, dict):
        for k, v in obj.items():
            if any(k.lower() == kk for kk in keys):
                return v
        # deeper search
        for k, v in obj.items():
            res = _find_in_obj(v, keys)
            if res is not None:
                return res
    elif isinstance(obj, list):
        for el in obj:
            res = _find_in_obj(el, keys)
            if res is not None:
                return res
    return None

def _guess_doc_name_from_response(resp):
    raw = getattr(resp, "_raw", None) or getattr(resp, "raw", None)
    if not isinstance(raw, dict):
        return None

    candidates = {}

    def walk(u):
        if isinstance(u, dict):
            # if a dict contains both id-like and name-like keys, map them
            id_key = None
            name_key = None
            for k in u.keys():
                kl = k.lower()
                if "id" in kl and ("file" in kl or "doc" in kl or "chunk" in kl or "name" in kl):
                    id_key = k
                if "name" in kl or "file" in kl or "display" in kl or "title" in kl:
                    name_key = k
            if id_key and name_key and isinstance(u.get(id_key), (str,int)) and isinstance(u.get(name_key), str):
                candidates[str(u.get(id_key))] = u.get(name_key)
            # also map direct file dicts
            if "file_name" in u and isinstance(u.get("file_name"), str):
                candidates[u.get("file_name")] = u.get("file_name")
            if "document_name" in u and isinstance(u.get("document_name"), str):
                candidates[u.get("document_name")] = u.get("document_name")
            # recursive
            for v in u.values():
                walk(v)
        elif isinstance(u, list):
            for el in u:
                walk(el)

    walk(raw)
    return candidates or None


def _normalize_chunk(ch, resp_for_lookup=None):
    text = None
    doc = None
    start = None
    end = None
    score = None

    # Try to convert SDK objects to dict-like
    try:
        if hasattr(ch, "to_dict"):
            ch = ch.to_dict()
        elif hasattr(ch, "dict"):
            ch = ch.dict()
    except Exception:
        pass

    # If it's a dict, inspect expected fields
    if isinstance(ch, dict):
        # 1) Common nested containers that hold text and doc
        for container_key in (
            "retrieved_context", "retrieved_contexts", "segment",
            "retrieval_segment", "rag_chunk", "retrieval", "content"
        ):
            if container_key in ch and isinstance(ch[container_key], dict):
                seg = ch[container_key]
                text = text or seg.get("text") or seg.get("rag_chunk") or seg.get("content")
                doc = doc or seg.get("document_name") or seg.get("file_name") or seg.get("document") or seg.get("source")
                start = start or seg.get("start_index") or seg.get("start")
                end = end or seg.get("end_index") or seg.get("end")

        # 2) Top-level text fields
        if text is None:
            text = ch.get("text") or ch.get("rag_chunk") or ch.get("chunk_text") or ch.get("retrieved_text") or ch.get("content")

        # 3) Top-level doc-like fields (look for many possible keys)
        doc = doc or ch.get("document_name") or ch.get("file_name") or ch.get("document") or ch.get("source") or ch.get("file")

        # 4) Score fields
        score = ch.get("score") or ch.get("confidence") or ch.get("confidence_score")

        # 5) start/end at top-level if present
        if start is None:
            start = ch.get("start_index") or ch.get("start")
        if end is None:
            end = ch.get("end_index") or ch.get("end")

        # 6) NEW: check for common "title"/"display_name"/"name" keys on chunk itself
        if doc is None:
            for key in ("title", "display_name", "name"):
                val = ch.get(key)
                if isinstance(val, str) and val.strip():
                    doc = val.strip()
                    break

        # 7) NEW: if still missing, check inside retrieved_context (if present) for title/display_name
        if doc is None:
            rc = ch.get("retrieved_context") or ch.get("retrieved_contexts") or ch.get("segment") or None
            if isinstance(rc, dict):
                for key in ("title", "display_name", "document_name", "file_name", "file"):
                    val = rc.get(key)
                    if isinstance(val, str) and val.strip():
                        doc = val.strip()
                        break

    else:
        # fallback: stringify
        text = str(ch)

    # If doc still missing, try to find mapping in the full response (e.g., id->name)
    if doc is None and resp_for_lookup is not None:
        mapping = _guess_doc_name_from_response(resp_for_lookup)
        # sometimes chunk contains an id field pointing to actual file - search for id-like keys
        id_candidate = _find_in_obj(ch, ["document_id", "file_id", "id", "documentId", "fileId", "chunk_id", "file_name"])
        if id_candidate:
            key = str(id_candidate)
            if mapping and key in mapping:
                doc = mapping[key]
        # if mapping contains any filename-like strings, pick the first as a last resort
        if doc is None and mapping:
            for k, v in mapping.items():
                if isinstance(k, str) and any(ext in k.lower() for ext in (".pdf", ".txt", ".doc", ".docx", ".md")):
                    doc = v or k
                    break
            if doc is None:
                for v in mapping.values():
                    doc = v
                    break

    # Final normalization
    text = (text or "").strip() if text is not None else None
    doc = doc or None
    return {"text": text, "doc": doc, "start": start, "end": end, "score": score}



def get_top_grounding_snippets(resp, top_n=3):
    """
    Return up to top_n normalized grounding snippets. Uses candidate-level grounding first,
    then top-level attributes, then raw fallback. Tries to discover document names.
    """
    snippets = []

    # candidate-level grounding (common)
    try:
        cand_list = getattr(resp, "candidates", None)
        if cand_list and len(cand_list) > 0:
            cand = cand_list[0]
            # try known names
            gm = (getattr(cand, "grounding_metadata", None)
                  or getattr(cand, "groundingMetadata", None)
                  or getattr(cand, "grounding", None)
                  or getattr(cand, "grounding_chunks", None)
                  or getattr(cand, "retrievals", None)
                  or getattr(cand, "sources", None))
            # try to normalize gm to dict/list
            try:
                if hasattr(gm, "to_dict"):
                    gm = gm.to_dict()
                elif hasattr(gm, "dict"):
                    gm = gm.dict()
            except Exception:
                pass

            if isinstance(gm, dict):
                # prioritize grounding_chunks or retrieved_chunks
                chunks = gm.get("grounding_chunks") or gm.get("retrieved_chunks") or gm.get("chunks") or gm.get("items")
                if isinstance(chunks, (list, tuple)):
                    for ch in chunks:
                        snippets.append(_normalize_chunk(ch, resp_for_lookup=resp))
            # supports/grounding_supports sometimes contain segments
            supports = None
            if isinstance(gm, dict):
                supports = gm.get("grounding_supports") or gm.get("groundingSupports") or gm.get("supports")
            if isinstance(supports, (list, tuple)):
                for s in supports:
                    seg = None
                    if isinstance(s, dict):
                        seg = s.get("segment") or s.get("retrieved_segment")
                    if seg:
                        snippets.append(_normalize_chunk(seg, resp_for_lookup=resp))
    except Exception:
        pass

    # top-level grounding attributes
    if len(snippets) < top_n:
        for attr in ("grounding_metadata", "grounding", "grounding_chunks", "retrievals", "sources", "citation_metadata"):
            val = getattr(resp, attr, None)
            if val:
                try:
                    if hasattr(val, "to_dict"):
                        val = val.to_dict()
                    elif hasattr(val, "dict"):
                        val = val.dict()
                except Exception:
                    pass
                if isinstance(val, dict):
                    chunks = val.get("grounding_chunks") or val.get("retrieved_chunks") or val.get("chunks") or val.get("items")
                    if isinstance(chunks, (list, tuple)):
                        for ch in chunks:
                            snippets.append(_normalize_chunk(ch, resp_for_lookup=resp))
                elif isinstance(val, (list, tuple)):
                    for el in val:
                        snippets.append(_normalize_chunk(el, resp_for_lookup=resp))

    # raw fallback search
    if len(snippets) < top_n:
        raw = getattr(resp, "_raw", None) or getattr(resp, "raw", None)
        def scan_for_chunks(obj):
            found = []
            if isinstance(obj, dict):
                for k, v in obj.items():
                    lk = k.lower()
                    if lk in ("grounding_chunks","retrieved_chunks","chunks","grounding","retrievals","sources","items"):
                        if isinstance(v, (list, tuple)):
                            for el in v:
                                found.append(el)
                        else:
                            found.append(v)
                    else:
                        found += scan_for_chunks(v)
            elif isinstance(obj, list):
                for el in obj:
                    found += scan_for_chunks(el)
            return found
        try:
            if isinstance(raw, dict):
                raw_chunks = scan_for_chunks(raw)
                for ch in raw_chunks:
                    snippets.append(_normalize_chunk(ch, resp_for_lookup=resp))
        except Exception:
            pass

    # dedupe and return top_n
    seen = set()
    unique = []
    for s in snippets:
        key = ((s.get("doc") or "").strip(), (s.get("text") or "")[:300])
        if key in seen:
            continue
        seen.add(key)
        unique.append(s)
        if len(unique) >= top_n:
            break

    return unique


def extract_text(resp):
    """Safely extract text from any Gemini response structure."""
    if getattr(resp, "text", None):
        return resp.text

    pieces = []

    for attr in ("candidates", "outputs", "output", "generations", "choices"):
        seq = getattr(resp, attr, None)
        if not seq:
            continue
        if not isinstance(seq, (list, tuple)):
            seq = [seq]
        for item in seq:
            # Common text fields
            for f in ("text", "content", "display_text"):
                if hasattr(item, f):
                    val = getattr(item, f)
                    if isinstance(val, str):
                        pieces.append(val)
                    else:
                        pieces.append(str(val))
            # Nested fields
            for sub in ("message", "completion", "result"):
                if hasattr(item, sub):
                    subobj = getattr(item, sub)
                    for f in ("text", "content"):
                        if hasattr(subobj, f):
                            val = getattr(subobj, f)
                            if isinstance(val, str):
                                pieces.append(val)
                            else:
                                pieces.append(str(val))
            pieces.append(str(item))

    raw = getattr(resp, "_raw", None) or getattr(resp, "raw", None)
    if isinstance(raw, dict):
        def scan(obj):
            if isinstance(obj, str):
                return [obj]
            out = []
            if isinstance(obj, dict):
                for k, v in obj.items():
                    out += scan(v)
            elif isinstance(obj, list):
                for el in obj:
                    out += scan(el)
            return out
        raw_text = scan(raw)
        for t in raw_text:
            if t and isinstance(t, str):
                pieces.append(t)

    pieces = [str(p).strip() for p in pieces if p and str(p).strip()]
    if pieces:
        return "\n\n".join(pieces)
    return None


def pretty_doc_name(raw_name: str) -> str:
    """
    Remove leading numeric timestamp + underscore (e.g. 1764340785_),
    replace underscores with spaces, trim extension optionally, and tidy casing.
    """
    if not raw_name:
        return "Unknown document"
    name = raw_name.strip()
    # remove leading digits + underscore(s)
    name = re.sub(r'^\d+_+', '', name)
    # optionally remove folder paths
    name = name.split('/')[-1].split('\\')[-1]
    # replace underscores with spaces, collapse multiple spaces
    name = re.sub(r'[_]+', ' ', name)
    # optionally remove common extensions but keep them if you want
    # keep_ext = True  # set False to strip .pdf/.txt
    keep_ext = True
    if not keep_ext:
        name = re.sub(r'\.(pdf|txt|docx|doc|md|pptx)$', '', name, flags=re.I)
    # trim and title-case lightly
    name = name.strip()
    # if it's all-lower/underscored, make it nicer
    if len(name) <= 60:
        name = name.title()
    return name



def _obj_to_plain(o):
    """Convert SDK/protobuf-like objects to plain Python types for display."""
    # dict-like
    if isinstance(o, dict):
        return {k: _obj_to_plain(v) for k, v in o.items()}
    # lists
    if isinstance(o, (list, tuple)):
        return [_obj_to_plain(x) for x in o]
    # objects with .to_dict() or .dict() (common patterns)
    for fn in ("to_dict", "dict", "as_dict"):
        if hasattr(o, fn) and callable(getattr(o, fn)):
            try:
                return _obj_to_plain(getattr(o, fn)())
            except Exception:
                pass
    # objects with __dict__
    if hasattr(o, "__dict__") and getattr(o, "__dict__"):
        try:
            return _obj_to_plain(vars(o))
        except Exception:
            pass
    # fallback to simple types (int/float/str/bool/None)
    if isinstance(o, (str, int, float, bool)) or o is None:
        return o
    # last resort: string representation
    try:
        return str(o)
    except Exception:
        return repr(o)


def extract_grounding(resp):
    """
    Attempt to extract grounding / retrieval / citation information from a model response.
    Returns a structured dict like:
      { "source": "<where found>", "items": [ ...normalized items... ] }
    or None if nothing reasonable is found.
    """

    # 1) Candidate-level grounding is common: response.candidates[*].grounding_metadata
    try:
        candidates = getattr(resp, "candidates", None)
        if candidates:
            items = []
            for i, cand in enumerate(candidates):
                # try several attribute names that may hold grounding
                gm = (getattr(cand, "grounding_metadata", None)
                      or getattr(cand, "groundingMetadata", None)
                      or getattr(cand, "grounding", None)
                      or getattr(cand, "grounding_chunks", None)
                      or getattr(cand, "retrievals", None)
                      or getattr(cand, "sources", None))
                if gm:
                    items.append({
                        "candidate_index": i,
                        "grounding": _obj_to_plain(gm)
                    })
            if items:
                return {"source": "candidates", "items": items}
    except Exception:
        # don't fail hard on unexpected SDK shapes
        pass

    # 2) Top-level attributes on the response object
    for attr in ("grounding_metadata", "grounding", "groundingMetadata", "grounding_chunks", "retrievals", "sources", "citation_metadata"):
        try:
            val = getattr(resp, attr, None)
            if val:
                return {"source": attr, "items": _obj_to_plain(val)}
        except Exception:
            continue

    # 3) Raw dict search (response._raw or response.raw)
    raw = getattr(resp, "_raw", None) or getattr(resp, "raw", None)
    if isinstance(raw, dict):
        # look for keys we care about and return their normalized content
        keys_of_interest = {"grounding", "grounding_metadata", "grounding_chunks", "retrievals", "sources", "citations", "references"}
        def find_keys(obj, path=""):
            found = []
            if isinstance(obj, dict):
                for k, v in obj.items():
                    lk = k.lower()
                    new_path = f"{path}.{k}" if path else k
                    if lk in keys_of_interest:
                        found.append({"path": new_path, "value": _obj_to_plain(v)})
                    # recursive search
                    found.extend(find_keys(v, new_path))
            elif isinstance(obj, list):
                for idx, el in enumerate(obj):
                    found.extend(find_keys(el, f"{path}[{idx}]"))
            return found

        matches = find_keys(raw, "")
        if matches:
            return {"source": "_raw", "items": matches}

    # Nothing found
    return None


def list_filestore_documents(client, file_search_store_name, api_key=None):
    """
    Returns a list of file/document metadata dicts from a File Search store.
    Tries SDK method first; falls back to REST API if needed.
    """
    # Try SDK route (some SDK versions: client.file_search_stores.documents.list)
    try:
        # Many SDKs expose a documents collection under file_search_stores
        docs_iter = client.file_search_stores.documents.list(parent=file_search_store_name)
        # docs_iter may be an iterator/generator — convert to list
        docs = list(docs_iter)
        # Convert SDK objects to plain dicts if possible
        def _plain(o):
            if hasattr(o, "to_dict"):
                try:
                    return o.to_dict()
                except Exception:
                    pass
            if hasattr(o, "dict"):
                try:
                    return o.dict()
                except Exception:
                    pass
            # fallback to __dict__ or str
            if hasattr(o, "__dict__"):
                try:
                    return dict(o.__dict__)
                except Exception:
                    pass
            return {"raw": str(o)}
        plain_docs = [_plain(d) for d in docs]
        return plain_docs
    except Exception as e_sdk:
        # SDK path failed (some versions had a bug). Fall back to REST.
        # Construct REST URL:
        # The REST path is: https://generativelanguage.googleapis.com/v1beta/{parent=fileSearchStores/*}/documents
        # parent should be the full store resource name, e.g. "fileSearchStores/my-store-123"
        if api_key is None:
            raise RuntimeError("SDK failed and no api_key provided for REST fallback. SDK error: " + str(e_sdk))
        url = f"https://generativelanguage.googleapis.com/v1beta/{file_search_store_name}/documents"
        headers = {"Authorization": f"Bearer {api_key}"}  # developer key should work here
        params = {"pageSize": 200}  # adjust if needed
        resp = requests.get(url, headers=headers, params=params, timeout=30)
        if not resp.ok:
            raise RuntimeError(f"REST fallback failed: {resp.status_code} {resp.text}")
        j = resp.json()
        # The REST body commonly returns {'documents': [...]} or similar
        items = j.get("documents") or j.get("items") or j.get("files") or []
        return items
    



# ---- App layout & initialization ----
st.set_page_config(page_title="File Search RAG", layout="wide")
st.title("RAG-File Search")

# Sidebar: Vertex controls + Import Progress area
st.sidebar.header("Deployment / Vertex settings")
use_vertex = st.sidebar.checkbox("Use VertexAI client (vertexai=True)", value=False, key="sidebar_use_vertex")
project = st.sidebar.text_input("GCP project (optional, only for VertexAI)", value=os.environ.get("GOOGLE_CLOUD_PROJECT", ""), key="sidebar_gcp_project")
location = st.sidebar.text_input("Location (optional)", value=os.environ.get("GOOGLE_CLOUD_LOCATION", "global"), key="sidebar_gcp_location")

# Sidebar import progress placeholders (will be updated by upload/poll)
st.sidebar.markdown("### Import progress")
sidebar_status_text = st.sidebar.empty()
sidebar_progress_bar = st.sidebar.progress(0)

def sidebar_status_text_set(msg: str):
    sidebar_status_text.text(msg)

def sidebar_status_progress_set(pct: int):
    try:
        sidebar_progress_bar.progress(pct)
    except Exception:
        pass

sidebar_status = {"text": sidebar_status_text_set, "progress": sidebar_status_progress_set}

# Top navigation: Home | Settings
tabs = st.tabs(["Home", "Settings", "Files"])
home_tab = tabs[0]
settings_tab = tabs[1]
filesStorage=tabs[2]

# ---- Settings tab: API KEY (nav button behavior) ----
with settings_tab:
    st.header("Settings")
    st.markdown("Paste your Gemini API key here. This is stored in the environment of the running process (not persisted to disk).")
    api_key_input = st.text_input("GEMINI API KEY (or set GEMINI_API_KEY env var)", value=os.environ.get("GEMINI_API_KEY", ""), type="password", key="settings_api_key")
    if st.button("Set API key", key="set_api_key_btn"):
        if api_key_input:
            os.environ["GEMINI_API_KEY"] = api_key_input.strip()
            st.success("GEMINI_API_KEY set in environment for this session.")
        else:
            st.error("Empty key — enter a valid API key.")

    st.markdown(
        """
        Notes:
        - For local quick tests, developer API key (`GEMINI_API_KEY`) is simplest.
        - For Vertex: set GOOGLE_APPLICATION_CREDENTIALS and enable Vertex authentication; use the sidebar to toggle Vertex and enter project/location.
        """
    )

# Initialize Gemini client (after settings)
# We initialize client on each run so changes to API_KEY or Vertex toggle take effect.
try:
    if use_vertex:
        client = genai.Client(vertexai=True, project=project or None, location=location or None)
    else:
        client = genai.Client()
except Exception as e:
    st.sidebar.error(f"Failed to initialize Gemini client: {e}")
    st.stop()

# ---- Home tab content ----
with home_tab:
    st.header("Home")

    # Create a store (left) and list your stores (right)
    col1, col2 ,col3= st.columns([1.5, 1 ,1.5])
    with col1:
        st.subheader("Create a store")
        new_store_name = st.text_input("Display name for new File Search store", key="create_store_name")
        if st.button("Create store", key="create_store_btn"):
            try:
                created = client.file_search_stores.create(config={"display_name": new_store_name or f"store-{int(time.time())}"})
                st.success(f"Created: {created.name}")
            except Exception as e:
                st.error(f"Create failed: {e}")

    with col2:
        st.subheader("Your stores")
        stores = []
        try:
            stores = list(client.file_search_stores.list())
        except Exception as e:
            st.warning(f"Could not list stores: {e}")
        store_map = {s.display_name or s.name: s for s in stores}
        if store_map:
            selected_store_label = st.selectbox("Select File Search store", options=list(store_map.keys()), key="select_store_box")
            selected_store = store_map[selected_store_label]
            st.write("Store name (use this in code):", selected_store.name)
        else:
            st.info("No File Search stores found — create one above or upload a file to create+import automatically.")
            selected_store = None
    with col3:
        if selected_store is not None:
            st.subheader("Files in selected File Search store")
            try:
                # call helper (provide API key for REST fallback)
                file_items = list_filestore_documents(client, selected_store.name, api_key=os.environ.get("GEMINI_API_KEY"))
                if not file_items:
                    st.info("No documents found in this File Search store.")
                else:
                    # Normalize to table-friendly rows
                    rows = []
                    for d in file_items:
                        # d might be dict already (SDK or REST). Try to grab common fields.
                        title = d.get("title") or d.get("display_name") or d.get("document_name") or d.get("file_name") or d.get("name")
                        created = d.get("create_time") or d.get("created_at") or d.get("createTime")
                        # attempt ISO -> pretty date
                        try:
                            if created:
                                dt = datetime.fromisoformat(created.replace("Z","+00:00"))
                                created = dt.strftime("%Y-%m-%d %H:%M:%S")
                        except Exception:
                            pass
                        size = d.get("size") or d.get("file_size") or d.get("bytes")
                        page_count = d.get("page_count") or d.get("pages") or None
                        doc_id = d.get("name") or d.get("id") or d.get("document_id") or title
                        rows.append({
                            "id": doc_id,
                            "title": title or "(no title)",
                            "created": created or "",
                            "pages": page_count or "",
                            "size": size or "",
                            "raw": d
                        })
                    df = pd.DataFrame(rows)
                    # Show an interactive table (ace tools will present DataFrame nicely)
                    st.dataframe(df[["title", "created", "pages", "size"]], height=300)
            except Exception as e:
                st.error(f"Failed to list files: {e}")
    st.markdown("---")

    # Upload & import UI (on home)
    st.subheader("Upload & import files into File Search store")
    upload_col1, upload_col2 = st.columns([2, 1])
    with upload_col1:
        upload_file = st.file_uploader("Choose a file to upload (PDF, TXT, DOCX, etc.)", accept_multiple_files=False, key="home_uploader")
        display_name = st.text_input("File display name (optional)", key="display_name_input")
    with upload_col2:
        chunk_max_tokens = st.number_input("Max tokens per chunk (optional)", min_value=0, max_value=2000, value=0, step=50, key="chunk_max_tokens_input")
        max_overlap = st.number_input("Max overlap tokens (optional)", min_value=0, max_value=1000, value=0, step=10, key="max_overlap_input")

    # Import button triggers upload; progress shown in sidebar
    if st.button("Import file into selected store", key="import_button"):
        if upload_file is None and selected_store is None:
            st.error("Upload a file or select/create a store first.")
        else:
            target_store = selected_store
            if target_store is None:
                st.info("No store selected — creating a temporary store...")
                try:
                    target_store = client.file_search_stores.create(config={"display_name": f"streamlit-store-{int(time.time())}"})
                    st.success(f"Created store {target_store.name}")
                except Exception as e:
                    st.error(f"Failed to create store: {e}")
                    st.stop()

            if upload_file is None:
                st.error("No file uploaded to import.")
                st.stop()

            # Read and save upload to temp path
            try:
                try:
                    upload_file.seek(0)
                except Exception:
                    pass
                try:
                    data = upload_file.getvalue()
                except Exception:
                    data = upload_file.read()
                if not data:
                    st.error("Uploaded file appears empty.")
                    st.stop()
                tmp_path = safe_write_tmp(data, upload_file.name)
            except Exception as e:
                st.error(f"Failed to save uploaded file: {e}")
                st.stop()

            # Build config once
            config = {}
            if chunk_max_tokens and int(chunk_max_tokens) > 0:
                config["chunking_config"] = {
                    "white_space_config": {
                        "max_tokens_per_chunk": int(chunk_max_tokens),
                        "max_overlap_tokens": int(max_overlap or 0),
                    }
                }
            if display_name:
                config["display_name"] = display_name

            # Update sidebar status before starting
            sidebar_status["text"]("Starting upload...")
            sidebar_status

            # Try upload with fallbacks
            try:
                op = robust_upload_to_store(client, tmp_path, target_store.name, config, sidebar_status)
            except Exception as e:
                sidebar_status["text"](f"Upload failed: {e}")
                st.error(f"Upload failed: {e}")
                # cleanup temp file
                try:
                    if os.path.exists(tmp_path):
                        os.remove(tmp_path)
                except Exception:
                    pass
                st.stop()

            # Poll operation and show progress in sidebar
            try:
                op = poll_operation(client, op, sidebar_status, timeout=300, interval=2)
                st.success("Import finished (or queued). File has been indexed into the selected File Search store.")
                st.write("Store:", target_store.name)
            except Exception as e:
                st.error(f"Error while waiting for import: {e}")
            finally:
                try:
                    if os.path.exists(tmp_path):
                        os.remove(tmp_path)
                except Exception:
                    pass

    st.markdown("---")

    if "rows" not in locals() or len(rows) == 0:
        st.warning("No documents available in the selected store.")
        st.stop()


def _extract_page_from_text(text):
    import re
    if not text:
        return None
    m = re.search(r'---\s*PAGE\s*(\d+)\s*---', text, re.I)
    if m:
        return m.group(1)

    m2 = re.search(r'\bpage[\s:]*([0-9]{1,3})\b', text, re.I)
    if m2:
        return m2.group(1)

    return None


# ---------- Ask (RAG) (updated with session persistence & safe guards) ----------
st.subheader("Ask questions (RAG)")

# --- If a previous Q/A is stored in session_state, render it first (persists across reruns) ---
if "last_answer" in st.session_state:
    # ensure a remembered expanded/collapsed preference exists
    if "persisted_expanded" not in st.session_state:
        st.session_state["persisted_expanded"] = True  # default expanded

    # Use an expander (collapsible). `expanded` uses remembered preference.
    with st.expander(
    f"Last Answer (persisted) — updated {st.session_state.get('last_updated_at','')}",
    expanded=st.session_state.get("persisted_expanded", True),
    ):
        # small toggle to remember whether the expander should be open by default
        st.checkbox(
            "Keep this section expanded by default",
            value=st.session_state.get("persisted_expanded", False),
            key="persisted_expander_checkbox",
        )
        # update remembered preference from checkbox (persist across reruns)
        st.session_state["persisted_expanded"] = st.session_state.get("persisted_expander_checkbox", True)

        st.subheader("Answer (persisted)")
        st.write(st.session_state.get("last_answer", "(no answer)"))

        last_sources = st.session_state.get("last_sources", [])
        if last_sources:
            st.markdown("**SOURCES:** " + "  \n\t ".join(last_sources))
        else:
            st.info("No sources stored for last answer.")

        last_snips = st.session_state.get("last_snippets", {}) or {}
        last_top = st.session_state.get("last_top_docs", list(last_snips.keys()))
        if last_top:
            st.subheader(f"Top {len(last_top)} sources / grounding snippets (persisted)")
            for i, doc in enumerate(last_top, start=1):
                st.markdown(f"**{i}. {doc}**")
                snips = last_snips.get(doc, [])
                for j, s in enumerate(snips, start=1):
                    txt = s.get("text", "")
                    excerpt = re.sub(r"\s+", " ", txt).strip()
                    if len(excerpt) > 600:
                        excerpt = excerpt[:600].rstrip() + "…"
                    page = _extract_page_from_text(txt) if callable(globals().get("_extract_page_from_text")) else None
                    if page:
                        st.markdown(f"**Snippet (page {page}):**")
                    else:
                        if len(snips) > 1:
                            st.markdown(f"**Snippet {j}:**")
                    st.write(excerpt)
                    meta = []
                    if s.get("start") is not None or s.get("end") is not None:
                        meta.append(f"pos: {s.get('start') or '?'}–{s.get('end') or '?'}")
                    if s.get("score") is not None:
                        try:
                            meta.append(f"score: {float(s.get('score')):.3f}")
                        except Exception:
                            meta.append(f"score: {s.get('score')}")
                    if meta:
                        st.caption(" · ".join(meta))
    st.markdown("---")

# --- Inputs ---
question = st.text_area("Enter your question", height=120, key="question_input")
model = st.selectbox("Model", options=["gemini-2.5-flash", "gemini-1.0"], index=0, key="model_select")
max_tokens = st.number_input(
    "Max output tokens", min_value=64, max_value=2000, value=512, step=64, key="max_output_tokens_input"
)

# --- Document selection (safe guards) ---
doc_title = None
sel_index = None
if "rows" in locals() and isinstance(rows, (list, tuple)) and len(rows) > 0:
    sel_index = st.selectbox(
        "Select file to Filter results.",
        options=list(range(len(rows))),
        format_func=lambda i: rows[i]["title"],
    )

selected_doc = rows[sel_index] if (sel_index is not None and "rows" in locals() and 0 <= sel_index < len(rows)) else None

try:
    if "rows" in locals() and isinstance(sel_index, int) and 0 <= sel_index < len(rows):
        doc_title = (
            rows[sel_index].get("title")
            or rows[sel_index].get("display_name")
            or rows[sel_index].get("raw", {}).get("title")
        )
    elif selected_doc and isinstance(selected_doc, dict):
        doc_title = (
            selected_doc.get("title")
            or selected_doc.get("display_name")
            or selected_doc.get("name")
        )
except Exception:
    doc_title = None

if not doc_title:
    doc_title = "(unspecified document)"

pretty = pretty_doc_name(doc_title or "(unspecified document)")

system_prompt = f"""
SYSTEM INSTRUCTIONS:
You are a grounded assistant that must prioritize content from the document named: {pretty}

1) PRIMARY RULE — Use the document named {pretty} as the primary source of truth:
- If the document contains sufficient content to answer the user's question, answer using only that content and include inline citation markers (e.g. [SOURCE: {pretty}: PAGE 1]) next to any statements directly taken from the document.
- When quoting or paraphrasing document text, include the exact page number if available.

2) FALLBACK RULE — If the document does NOT contain the needed information:
- Generate a complete, correct answer using general knowledge.
- Prefix any generated paragraph with: [GENERATED].
- Prefix any inference beyond the document with: [INFERRED] and briefly explain the reasoning.

3) CITATIONS:
- List document(s) used and page numbers in a SOURCES section at the end in this format:
    SOURCES:
    - {pretty}: PAGE <n>

4) ANSWER STYLE:
- Provide a short summary (2-4 sentences) first.
- Then provide step-by-step explanation or runnable code if relevant.
- Use code fences and specify language for code blocks.

5) SAFETY:
- Do not fabricate direct quotations from the document.
- If you cannot answer using the document and cannot safely generate an answer, say: "I cannot answer from the provided document."

EXAMPLE:
If the provided document only lists questions, you should still provide a solution but mark it like:
[GENERATED] Here is a complete solution...
SOURCES:
- {pretty}: (document contained the question but no solution)
"""

# --- Ask action ---
if st.button("Ask", key="ask_button_home"):
    if not question.strip():
        st.error("Type a question.")
    elif selected_store is None:
        st.error("Select or create a File Search store that contains your docs.")
    else:
        st.info("Querying Gemini with File Search as a tool...")
        try:
            # Build FileSearch tool config
            fs_tool = types.Tool(file_search=types.FileSearch(file_search_store_names=[selected_store.name]))
            cfg = types.GenerateContentConfig(max_output_tokens=int(max_tokens), tools=[fs_tool])

            # Call the model
            contents = [system_prompt, question]
            response = client.models.generate_content(model=model, contents=contents, config=cfg)

            # Extract answer and show
            answer_text = extract_text(response)
            st.subheader("Answer")
            st.write(answer_text or "No text answer found (see raw)")

            # Get grounding snippets
            raw_top_snips = get_top_grounding_snippets(response, top_n=10)

            # Deduplicate and normalize snippets
            unique_snips = []
            seen_texts = set()
            for s in raw_top_snips:
                text = (s.get("text") or "").strip()
                if not text:
                    continue
                key = text[:1000]
                if key in seen_texts:
                    continue
                seen_texts.add(key)
                unique_snips.append(s)

            # Group by pretty doc name
            by_doc = {}
            doc_order = []
            for s in unique_snips:
                raw_doc = (s.get("doc") or "Unknown document")
                if isinstance(raw_doc, str):
                    raw_doc = raw_doc.strip()
                pretty_name = pretty_doc_name(raw_doc)
                if pretty_name not in by_doc:
                    by_doc[pretty_name] = []
                    doc_order.append(pretty_name)
                by_doc[pretty_name].append(s)

            # Pick best snippets per doc (score then length), collect pages
            selected_per_doc = {}
            doc_pages = {}
            for doc in doc_order:
                snips = by_doc.get(doc, [])

                def _score_key(x):
                    sc = x.get("score")
                    scv = (
                        float(sc)
                        if isinstance(sc, (int, float, str))
                        and str(sc).replace(".", "", 1).lstrip("-").isdigit()
                        else None
                    )
                    text_len = len((x.get("text") or ""))
                    return (scv if scv is not None else -1.0, text_len)

                snips_sorted = sorted(snips, key=_score_key, reverse=True)

                picked = []
                picked_pages = []
                for s in snips_sorted:
                    txt = (s.get("text") or "").strip()
                    page = _extract_page_from_text(txt) or None
                    if page and page in picked_pages:
                        continue
                    picked.append(s)
                    if page:
                        picked_pages.append(page)
                    if len(picked) >= 2:
                        break

                if not picked and snips_sorted:
                    picked = [snips_sorted[0]]

                selected_per_doc[doc] = picked
                if picked_pages:
                    doc_pages[doc] = picked_pages
                else:
                    all_pages = []
                    for s in snips:
                        p = _extract_page_from_text(s.get("text") or "")
                        if p and p not in all_pages:
                            all_pages.append(p)
                    if all_pages:
                        doc_pages[doc] = all_pages

            # Choose top K docs
            K = 3
            top_docs = doc_order[:K]

            # Build SOURCES line and display
            sources = []
            for d in top_docs:
                pages = doc_pages.get(d)
                if pages:
                    sources.append(f"{d}: PAGE {', '.join(str(p) for p in pages)}")
                else:
                    sources.append(d)

            if sources:
                st.markdown("**SOURCES:** " + "  \n\t ".join(sources))
            else:
                st.info("No grounding snippets found (model did not return explicit sources).")

            # Render snippets
            if top_docs:
                st.subheader(f"Top {len(top_docs)} sources / grounding snippets")
                shown_texts = set()
                for i, doc in enumerate(top_docs, start=1):
                    picks = selected_per_doc.get(doc, [])
                    if not picks:
                        continue
                    st.markdown(f"**{i}. {doc}**")
                    for j, s in enumerate(picks, start=1):
                        text = (s.get("text") or "(no snippet text available)").strip()
                        excerpt = re.sub(r"\s+", " ", text)
                        max_len = 600
                        if len(excerpt) > max_len:
                            excerpt = excerpt[:max_len].rstrip() + "…"
                        if excerpt in shown_texts:
                            continue
                        shown_texts.add(excerpt)
                        page = _extract_page_from_text(text)
                        if page:
                            st.markdown(f"**Snippet (page {page}):**")
                        else:
                            if len(picks) > 1:
                                st.markdown(f"**Snippet {j}:**")
                        st.write(excerpt)
                        meta = []
                        start = s.get("start")
                        end = s.get("end")
                        score = s.get("score")
                        if start is not None or end is not None:
                            meta.append(f"pos: {start or '?'}–{end or '?'}")
                        if score is not None:
                            try:
                                score_str = f"{float(score):.3f}"
                            except Exception:
                                score_str = str(score)
                            meta.append(f"score: {score_str}")
                        if meta:
                            st.caption(" · ".join(meta))

            # Persist the current Q/A (safe trimmed snippets to avoid huge session state)
            st.session_state["last_question"] = question
            st.session_state["last_doc_title"] = doc_title
            st.session_state["last_answer"] = answer_text or "(no answer returned)"
            st.session_state["last_sources"] = sources if isinstance(sources, list) else (sources or [])
            _trim_snips = {}
            for d, snips in selected_per_doc.items():
                _trim_snips[d] = []
                for s in snips[:2]:
                    _trim_snips[d].append({
                        "text": (s.get("text") or "")[:5000],
                        "start": s.get("start"),
                        "end": s.get("end"),
                        "score": s.get("score"),
                    })
            st.session_state["last_snippets"] = _trim_snips
            st.session_state["last_top_docs"] = top_docs if "top_docs" in locals() else list(_trim_snips.keys())
            st.session_state["last_updated_at"] = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

            # ----------------- Export / Save Chat (MD/HTML/PDF) -----------------
            def _make_markdown_export(title, question, answer_text, sources_list, selected_snippets):
                md = []
                md.append(f"# {title}")
                md.append("")
                md.append(f"**Question:**  \n{question}")
                md.append("")
                md.append("## Answer")
                md.append("")
                md.append(answer_text or "")
                md.append("")
                md.append("## SOURCES")
                if sources_list:
                    for s in sources_list:
                        md.append(f"- {s}")
                else:
                    md.append("- (none)")
                md.append("")
                if selected_snippets:
                    md.append("## Grounding snippets")
                    for doc, snips in selected_snippets.items():
                        md.append(f"### {doc}")
                        for s in snips:
                            page = _extract_page_from_text(s.get("text") or "")
                            header = f"(page {page})" if page else ""
                            md.append(f"- {header} { (s.get('text') or '').strip()[:1000] }")
                            md.append("")
                return "\n".join(md)

            def _make_html_export(title, question, answer_text, sources_list, selected_snippets):
                html_parts = []
                html_parts.append(f"<html><head><meta charset='utf-8'><title>{title}</title></head><body>")
                html_parts.append(f"<h1>{title}</h1>")
                html_parts.append(f"<h2>Question</h2><p>{question}</p>")
                html_parts.append(f"<h2>Answer</h2><div>{answer_text.replace(chr(10), '<br/>')}</div>")
                html_parts.append("<h2>Sources</h2><ul>")
                if sources_list:
                    for s in sources_list:
                        html_parts.append(f"<li>{s}</li>")
                else:
                    html_parts.append("<li>(none)</li>")
                html_parts.append("</ul>")
                if selected_snippets:
                    html_parts.append("<h2>Grounding snippets</h2>")
                    for doc, snips in selected_snippets.items():
                        html_parts.append(f"<h3>{doc}</h3>")
                        for s in snips:
                            page = _extract_page_from_text(s.get("text") or "")
                            header = f"(page {page})" if page else ""
                            snippet_html = (s.get("text") or "").replace("\n", "<br/>")
                            html_parts.append(f"<p><strong>{header}</strong> {snippet_html[:3000]}</p>")
                html_parts.append("</body></html>")
                return "\n".join(html_parts)

            # Build safe export pieces from persisted/session data
            export_title = pretty_doc_name(doc_title or "(unspecified document)")
            export_question = question or ""
            export_answer = answer_text or "(no answer returned)"
            export_sources_list = sources.copy() if isinstance(sources, list) else ([sources] if sources else [])
            selected_for_export = st.session_state.get("last_snippets", {})

            # Build selected_for_export robustly
            selected_for_export = {}
            if "selected_per_doc" in locals() and "top_docs" in locals():
                for d in top_docs:
                    selected_for_export[d] = selected_per_doc.get(d, [])[:2]
            elif "selected_per_doc" in locals() and "doc_order" in locals():
                for d in doc_order:
                    selected_for_export[d] = selected_per_doc.get(d, [])[:2]
            elif "by_doc" in locals():
                for doc_name, snips in by_doc.items():
                    selected_for_export[doc_name] = snips[:2]
            elif "raw_top_snips" in locals():
                temp = {}
                for s in raw_top_snips:
                    raw_doc = (s.get("doc") or "Unknown document")
                    if isinstance(raw_doc, str):
                        raw_doc = raw_doc.strip()
                    pretty_name = pretty_doc_name(raw_doc)
                    temp.setdefault(pretty_name, []).append(s)
                for k, v in temp.items():
                    selected_for_export[k] = v[:2]
            else:
                selected_for_export = {}

            # limit export size
            MAX_DOC_EXPORT = 10
            for k in list(selected_for_export.keys())[MAX_DOC_EXPORT:]:
                selected_for_export.pop(k, None)

            def _make_md_bytes():
                md = [f"# {export_title}", "", f"**Question:**  \n{export_question}", "", "## Answer", "", export_answer, "", "## SOURCES"]
                if export_sources_list:
                    md += [f"- {s}" for s in export_sources_list]
                else:
                    md.append("- (none)")
                md.append("")
                if selected_for_export:
                    md.append("## Grounding snippets")
                    for doc, snips in selected_for_export.items():
                        md.append(f"### {doc}")
                        for s in snips:
                            p = _extract_page_from_text(s.get("text") or "") if callable(globals().get("_extract_page_from_text")) else ""
                            hdr = f"(page {p})" if p else ""
                            md.append(f"- {hdr} { (s.get('text') or '').strip()[:1000] }")
                            md.append("")
                return ("\n".join(md)).encode("utf-8")

            def _make_html_bytes():
                html = ["<html><body>"]
                html.append(f"<h1>{export_title}</h1>")
                html.append(f"<h2>Question</h2><p>{export_question}</p>")
                html.append(f"<h2>Answer</h2><div>{export_answer.replace(chr(10), '<br/>')}</div>")
                html.append("<h2>Sources</h2><ul>")
                if export_sources_list:
                    html += [f"<li>{s}</li>" for s in export_sources_list]
                else:
                    html.append("<li>(none)</li>")
                html.append("</ul>")
                if selected_for_export:
                    html.append("<h2>Grounding snippets</h2>")
                    for doc, snips in selected_for_export.items():
                        html.append(f"<h3>{doc}</h3>")
                        for s in snips:
                            snippet_html = (s.get("text") or "").replace("\n", "<br/>")
                            html.append(f"<p>{snippet_html[:3000]}</p>")
                html.append("</body></html>")
                return ("\n".join(html)).encode("utf-8")

            md_bytes = _make_md_bytes()
            html_bytes = _make_html_bytes()

            # Offer MD / HTML / PDF downloads (PDF via reportlab when available)
            dlc1, dlc2, dlc3 = st.columns([1, 1, 1])

            with dlc1:
                st.download_button(
                    "Download last chat as MD",
                    data=md_bytes,
                    file_name="last_chat.md",
                    mime="text/markdown",
                )

            with dlc2:
                st.download_button(
                    "Download last chat as HTML",
                    data=html_bytes,
                    file_name="last_chat.html",
                    mime="text/html",
                )

            with dlc3:
                # Try to build a PDF using reportlab. If reportlab missing or fails, show hint.
                try:
                    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
                    from reportlab.lib.styles import getSampleStyleSheet
                    from reportlab.lib.pagesizes import letter
                    from reportlab.lib.units import inch

                    pdf_io = io.BytesIO()
                    doc_pdf = SimpleDocTemplate(
                        pdf_io,
                        pagesize=letter,
                        rightMargin=inch / 2,
                        leftMargin=inch / 2,
                        topMargin=inch / 2,
                        bottomMargin=inch / 2,
                    )
                    styles = getSampleStyleSheet()
                    normal = styles["Normal"]
                    normal.spaceAfter = 6
                    title_style = styles["Title"]

                    story = []
                    story.append(Paragraph(export_title, title_style))
                    story.append(Spacer(1, 6))
                    story.append(Paragraph(f"<b>Question</b>: {export_question}", normal))
                    story.append(Spacer(1, 6))
                    story.append(Paragraph("<b>Answer</b>:", normal))

                    # Add answer paragraphs (preserve basic newlines)
                    for para in str(export_answer).split("\n\n"):
                        story.append(Paragraph(para.replace("\n", "<br/>"), normal))
                        story.append(Spacer(1, 4))

                    story.append(Spacer(1, 6))
                    story.append(Paragraph("<b>SOURCES</b>:", normal))
                    if export_sources_list:
                        for s in export_sources_list:
                            story.append(Paragraph(f"- {s}", normal))
                    else:
                        story.append(Paragraph("- (none)", normal))

                    if selected_for_export:
                        story.append(Spacer(1, 6))
                        story.append(Paragraph("<b>Grounding snippets</b>", normal))
                        for doc_name, snips in selected_for_export.items():
                            story.append(Spacer(1, 4))
                            story.append(Paragraph(f"<b>{doc_name}</b>", normal))
                            for s in snips:
                                txt = (s.get("text") or "").strip()
                                if not txt:
                                    continue
                                txt_snip = txt.replace("\n", " ")
                                if len(txt_snip) > 3000:
                                    txt_snip = txt_snip[:3000] + "…"
                                story.append(Paragraph(txt_snip, normal))
                                story.append(Spacer(1, 4))

                    doc_pdf.build(story)
                    pdf_bytes = pdf_io.getvalue()

                    st.download_button(
                        "Download last chat as PDF (.pdf)",
                        data=pdf_bytes,
                        file_name="last_chat.pdf",
                        mime="application/pdf",
                    )

                except Exception as pdf_e:
                    # Most common cause: reportlab not installed. Provide helpful hint.
                    st.info("PDF export unavailable (reportlab not installed or failed). Install it with `pip install reportlab` to enable PDF export.")
                    # Optionally show debug info in dev mode:
                    # st.write(str(pdf_e))

        except Exception as e:
            st.error(f"Request failed: {e}")
# ---------- end Ask (RAG) ----------


with filesStorage:
    st.write("File Storage")